tensorflow/serving

- tensorflow_serving/session_bundle/example/export_half_plus_two.py
- tensorflow_serving/session_bundle/exporter.py
Fix issue #21, to make "serving/tensorflow_serving/session_bundle/example/export_half_plus_two.py" and "serving/tensorflow_serving/session_bundle/exporter.py" support both python 2.7 and python 3.4.
> Fix issue #21,support both python 2.7 and python 3.4

- WORKSPACE
- tensorflow_serving/test_util/test_util.cc
Bazel is going to be restructuring the runfiles tree (see
https://github.com/bazelbuild/bazel/wiki/Updating-the-runfiles-tree-structure
for details), which requires all projects to have a workspace name
(`__main__` will be used if one is not provided).
Feel free to suggest a different name if you guys prefer, but something
needs to be set or the tests will break when Bazel starts using the new
runfiles tree structure.
> Add a workspace name

- tensorflow_serving/core/BUILD
This test is timeout flaky on ci.bazel.io, see:
http://ci.bazel.io/job/TensorFlow_Serving/81/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/console
http://ci.bazel.io/job/TensorFlow_Serving/84/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/console
> Increases //tensorflow_serving/core:basic_manager_test test size

- tensorflow_serving/example/mnist_inference.cc
- tensorflow_serving/example/mnist_inference_2.cc
I didn't notice these typos when I submitted pull request #73 a few days ago.
> Remaining typo fixes: minist -> mnist

- tensorflow_serving/example/inception_export.py
Inception reserves class id zero as a "background" class.  To account for this code which maps from class id to description subtracts one from the class id to get the correct description index.  This simplifies that logic by adding a "background" description in index zero which makes the class index and description index match.  In the event the model returns index zero we will now print the correct result.
> Update inception description lookup code

- tensorflow_serving/example/inception_client.py
- tensorflow_serving/example/inception_export.py
- tensorflow_serving/example/mnist_client.py
- tensorflow_serving/example/mnist_export.py
- tensorflow_serving/example/mnist_input_data.py
While going through the examples I came across a few instances of `#!/usr/grte/v4/bin/python2.7`. `grte/v4` is an internal Google tool, right? This pull request sets a standard shebang line.
> Remove `grte/v4` from examples

- WORKSPACE
- tensorflow_serving/g3doc/setup.md
- tensorflow_serving/tools/docker/Dockerfile.devel
Receiving the following issues when attempting to build `serving@master` with the included Dockerfile:
```
bazel build --ignore_unsupported_sandboxing -c opt tensorflow_serving/...
INFO: Reading 'startup' options from /root/.bazelrc: --batch
ERROR: /root/.cache/bazel/_bazel_root/1b03e6b0b95a8320062041ca0659e00e/external/org_tensorflow/tensorflow/tensorflow.bzl:571:26: Traceback (most recent call last):
File "/root/.cache/bazel/_bazel_root/1b03e6b0b95a8320062041ca0659e00e/external/org_tensorflow/tensorflow/tensorflow.bzl", line 565
rule(attrs = {"srcs": attr.label_list..."), <3 more arguments>)}, <2 more arguments>)
File "/root/.cache/bazel/_bazel_root/1b03e6b0b95a8320062041ca0659e00e/external/org_tensorflow/tensorflow/tensorflow.bzl", line 571, in rule
attr.label_list(cfg = "data", …
```
> Address issue with serving build errors on Bazel 0.3.0

- .gitignore
`/bazel-tensorflow_serving` is built and stored in the repository root, this will prevent it from being tracked.
> Ignore built /bazel-tensorflow_serving file

- tensorflow_serving/model_servers/main.cc
- tensorflow_serving/model_servers/tensorflow_model_server_test.py
Add an option on the command line for changing the default 30s file system poll wait interval.
> add command line option for file system poll wait (seconds)

- tensorflow_serving/example/inception_k8s.json
Existing example file points to a now non-existent 'inception_inference' file. This points now to the tensorflow_model_server.
> Fixes #201 - Update inception_k8s.json config

- tensorflow_serving/example/inception_k8s.json
- tensorflow_serving/g3doc/serving_inception.md
- Switches out replication controller in favor of deployment 
- Switches out JSON kubernetes configuration format in favor of YAML
- Fixes broken links in tutorial markdown
- Fixes broken arguments in kubernetes config
- Updates tutorial markdown
> Switch replication controller to deployment

- tensorflow_serving/g3doc/serving_advanced.md
- tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc
- tensorflow_serving/sources/storage_path/file_system_storage_path_source.proto
- tensorflow_serving/sources/storage_path/file_system_storage_path_source_test.cc
Modify `FileSystemStoragePathSource` to emit all versions rather than just the latest version if the following environment variable is set `TF_SERVING_MULTIPLE_VERSIONS` is set to true.
This does not change the default behavior of only serving the latest version.
This is discussed in the following Github issue :
https://github.com/tensorflow/serving/issues/197
> Add options to serve multiple versions of model

- tensorflow_serving/config/BUILD
- tensorflow_serving/config/model_server_config.proto
- tensorflow_serving/model_servers/main.cc
- tensorflow_serving/model_servers/server_core.cc
Add flag to model_server to enable serving of multiple versions of models (https://github.com/tensorflow/serving/pull/217).
> add flag for multiple version on command line

- tensorflow_serving/example/inception_k8s.yaml
I tried to follow the inception_serving tutorial, but got:
```
inception-deployment-3636006731-233j2   0/1       ErrImagePull   0          7s
```
after creating the deployment and service. I checked to see if the specified image:
`gcr.io/tensorflow-serving/inception:0.2.0` exists with:
```shell
$ gcloud beta container images list-tags gcr.io/tensorflow-serving/inception
DIGEST        TAGS    TIMESTAMP            GIT_SHA  VULNERABILITIES  FROM  BUILD
b60c79ea19c6  latest  2016-03-21T16:14:30
```
and saw that there is only one published tag, `latest`.
> Switch the tag from 0.2.0 to latest.

- tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc
Hi! 👋 
I'm using the new `export_savedmodel` API to export my tf.contrib.learn model to what is called a *saved model*. In contrast to the normal `export` method it creates a directory that is named by the current timestamp (millisecond precision) instead of the global step. When the model server converts the directory name to the version number for the servable an integer overflow occurs and causes the following error:
```
I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:324] File-system polling update: Servable:{name: nubbel version: -627989529}; Servable path: /data/exports/nubbel/1481135727591; Polling frequency: 100
I tensorflow_serving/core/basic_manager.cc:653] Successfully reserved resources to load servable {name: nubbel version: -627989529}
I …
```
> Fix integer overflow in version number

- tensorflow_serving/example/BUILD
- tensorflow_serving/example/inception_client.cc
#281 
This is a gRPC client which written in C++ and can run with the inception serving demo.
Build this demo with the following command:
bazel build tensorflow_serving/example:inception_client_cc
And run:
bazel-bin/tensorflow_serving/example/inception_client_cc --image=/file/to/my_cat.jpg
> Add a gRPC client in C++ for inception serving.

- tensorflow_serving/servables/tensorflow/BUILD
I'm trying to use serving as a submodule. When building it complained that //tensorflow_serving/servables/tensorflow:predict_impl was not visible. I've added the public visibility to it.
I hope this is ok.
> Adds public visibility to predict_impl cc_library

- tensorflow_serving/example/BUILD
- tensorflow_serving/workspace.bzl
Tensorflow-serving issue 354: [https://github.com/tensorflow/serving/issues/354](https://github.com/tensorflow/serving/issues/354)
When the inception repository name is the same as the inception model workspace name this results in anomalous behavior of tensorflow_serving/example build. 
Running the command 
```
bazel-bin/tensorflow_serving/example/inception_saved_model --checkpoint_dir=inception-v3 --output_dir=inception-export
```
fails because a needed support module cannot be loaded.
When the repository name is different than the workspace, a build time warning is generated.
This pull request provides a way to have the repository name be different than the inception workspace name (allowing the examples' build to work) and correct for the build time workspace/repository name mismatch …
> Fix issue with inception_saved_model build - issue 354 - v2

- tensorflow_serving/example/inception_export.py
- tensorflow_serving/example/inception_saved_model.py
- tensorflow_serving/example/mnist_export.py
- tensorflow_serving/example/mnist_saved_model.py
- tensorflow_serving/servables/tensorflow/testdata/export_bad_half_plus_two.py
- tensorflow_serving/servables/tensorflow/testdata/export_half_plus_two.py
Switch deprecated calls to newer functions:
- `tf.contrib.lookup.index_to_string` to `tf.contrib.lookup.index_to_string_table_from_tensor`
- `tf.initialize_all_tables` to `tf.tables_initializer`
- `tf.initialize_all_variables` to `tf.global_variables_initializer`
> Remove deprecated calls and upgrade them to newer ones in examples

- tensorflow_serving/model_servers/BUILD
Related to https://github.com/tensorflow/serving/issues/359 .
Now we can export and load the models from HDFS instead of local file system or Google Storage with this change.
Hope it can be merged.
> Add hdfs_file_system in BUILD file

- tensorflow_serving/tools/docker/Dockerfile.devel
Addresses tf_serving issue #122 - the mnist example causes a grpc error when run within a Docker container.
Summary:
- grpcio 0.15 causes a grpc error in the mnist_client.py example
- https://testpypi.python.org/simple/grpcio does not feature the latest grpcio releases. 
Example:
Server:
```
$> docker run -p 127.0.0.1:9000:9000 -v /host/path/to/exported/models:/models --name=tensorflow_container -it $USER/tensorflow-serving-devel
[..]
$> bazel build //tensorflow_serving/model_servers:tensorflow_model_server
$> bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=9000 --model_name=mnist --model_base_path=/models/mnist_model/
```
Client:
```
$> docker exec -it tensorflow_container bash
$> bazel-bin/tensorflow_serving/example/mnist_client --num_tests=1000 …
```
> Install grpcio from pypi.python.org and require minimum version 1.1.3

- tensorflow_serving/tools/docker/Dockerfile.devel
Add locate to installed packages in Dockerfile to support locate command in tensorflow configure script.
Following the [instructions](https://tensorflow.github.io/serving/docker) for configuring tensorflow serving in the docker container, the configure script errors out at line 254 when attempting to run the "locate" command. This is recent code that was committed in [this commit](https://github.com/tensorflow/tensorflow/commit/27dd167c5fd4d0d4e7572cc8d639c0e61e69215e)
Installing the locate package via the Dockerfile solves this issue.
> Add locate to installed packages in Dockerfile 

- tensorflow_serving/tools/docker/Dockerfile.devel
When building serving with [docker file](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel), I noticed only bazel is built but not serving binary. So I add this piece to the docker file. Please review.
> Add build for CPU

- tensorflow_serving/tools/docker/Dockerfile.devel
The imagenet training script uses wget to download datasets and fails since it cannot find wget command in the docker container. Hence adding wget to the list would solve it.
> add wget to list of apps to be installed

- tensorflow_serving/apis/BUILD
- tensorflow_serving/example/BUILD
- tensorflow_serving/model_servers/BUILD
- tensorflow_serving/servables/tensorflow/testdata/BUILD
Hi all~
I've used tf to train my model with Anaconda3 (python 3.6), and I want to deploy it using this tf-serving.
But when I build it with ```--force_python=py3 ```, it seems some examples are missing the ```srcs_version = "PY2AND3"``` annotation in BUILD files.
I've succeeded in building tf-serving and runing with python 3.6 after adding these annotations.
> Add srcs_version = "PY2AND3" in BUILD files

- tensorflow_serving/tools/docker/Dockerfile.devel-gpu
The Gpu Docker does not build on master (#540) for several reasons 
1) Tensorflow defaults to cudadnn_6.0
2) The issue raised and solved in 
https://github.com/tensorflow/serving/issues/327#issuecomment-282207825
This PR solves these two issues and the resulting docker image builds and passes all
> Update gpu docker file

- WORKSPACE
- tensorflow_serving/g3doc/setup.md
- tensorflow_serving/tools/docker/Dockerfile.devel
- tensorflow_serving/tools/docker/Dockerfile.devel-gpu
The bazel build step requires a minimum bazel version of `0.5.4`. The Dockerfile currently uses bazel `0.5.1` (which is too low). I've tested locally on my Macbook Pro - build ok with bazel `0.5.4` docker container.
To replicate test [follow instruction at](https://github.com/Atlas7/How-to-Deploy-a-Tensorflow-Model-in-Production/blob/mymaster/demo.ipynb) - but with bazel version `0.5.4`.
> use bazel 0.5.4 in Dockerfile

- tensorflow_serving/tools/docker/Dockerfile.devel-gpu
This docker was built and tested today with the following:
Nvidia driver 384.81. Cuda8; Cudnn6; K80 GPUs.
Nvidia docker:
wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.1/nvidia-docker-1.0.1-1.x86_64.rpm
sudo rpm -i /tmp/nvidia-docker*.rpm && rm /tmp/nvidia-docker*.rpm
sudo systemctl start nvidia-docker
> Working GPU docker: Nvidia driver 384.81;Cuda8 CuDNN6 bazel 5.4

- tensorflow_serving/g3doc/serving_basic.md
Adds a link to the MNIST For ML Beginners tutorial, which is currently referred to with text alone.
> Adds a link to the referenced tutorial

- tensorflow_serving/g3doc/serving_basic.md
The example code copied from https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/mnist_saved_model.py to `g3doc/serving_basic.md` was out of date with a recent (~4 months ago) change in the original source file. This PR updates the code snippet in the Markdown file.
> Sync code example in docs with original source file

- tensorflow_serving/model_servers/main.cc
With "per_process_gpu_memory_fraction" flag (1-100), the users can config per_process_gpu_memory_fraction, otherwise the server process will occupy all the gpu memory.
> add flag to config per_process_gpu_memory_fraction

- tensorflow_serving/g3doc/setup.md
Also add a passive-aggressive link to the closed issue.
Slightly tongue-in-cheek, but issue #700 really should be reopened.
> Clarify that the API works in Python 3.

- tensorflow_serving/example/inception_saved_model.py
- tensorflow_serving/example/mnist_saved_model.py
This makes the examples compatible with python3 (and matches the client code in this directory, which already uses `print_function`).
> Use print function for python3 compatibility.

- tensorflow_serving/model_servers/main.cc
- tensorflow_serving/model_servers/tensorflow_model_server_test.py
This change makes it possible to pass channel arguments to gRPC when starting the model server.
With this change we can get the behaviour we need when using an L4 load balancer in front of an auto scaling group in AWS.
> Add possibility to specify grpc channel args

- tensorflow_serving/tools/pip_package/build_pip_package.sh
Right now pip packages don't include meta model query `pb2.py` so that user can't query model status through grpc
This pr add them
> add meta model proto files to pip package

- WORKSPACE
Updating io_bazel_rules_closure and tensorflow versions to match latest tensorboard io_bazel_rules_closure version, in anticipation of upcoming new tensorboard plugins that involve use of servo
> update TF version

- tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc
TF  serving is [failing on Bazel CI](https://buildkite.com/bazel/tensorflow-serving/builds/746) since https://github.com/tensorflow/serving/commit/c42810c1e149269d3bdeefa0fca56092215b1bb6 where http_rest_prediction_handler_test was introduced.
The error looks like a compiler bug according to https://github.com/nlohmann/json/issues/109
This change should make it work with old gcc version.
> Fix a compilation error with old gcc compiler

- tensorflow_serving/g3doc/serving_basic.md
- Added repo cloning instructions
- Updated shell prompt to "$ ", so that syntax highlighting shows it correctly, and unified across the entire document
> Repo cloning and shell prompt in example readme

- tensorflow_serving/g3doc/docker.md
This PR simply fixes an incorrect link to `Dockerfile.devel-gpu` in the documentation.
> Fix an incorrect link to Dockerfile.devel-gpu

- tensorflow_serving/example/mnist_saved_model.py
Since Python 3 has dropped `xrange()`, we should always use `range()` in the future.
> Add support for Python 3 while still compatible with Python 2.7

- tensorflow_serving/tools/pip_package/BUILD
- tensorflow_serving/tools/pip_package/build_pip_package.sh
- tensorflow_serving/tools/pip_package/setup.py
In tensorflow-serving-api, [get_model_status](https://github.com/tensorflow/serving/blob/1.9.0/tensorflow_serving/apis/BUILD#L236-L244) requires a generated code from status.proto in util.
```
>>> from tensorflow_serving.apis import get_model_status_pb2
...
ImportError: No module named util
```
> Add util for get model status

- tensorflow_serving/config/BUILD
- tensorflow_serving/config/ssl_config.proto
- tensorflow_serving/model_servers/BUILD
- tensorflow_serving/model_servers/main.cc
This is code to add support for secure channel to the modelserver, as requested in https://github.com/tensorflow/serving/issues/193.  You should find me under the SAP corporate CLA agreement contributor list.
> Adding support for secure channel to modelserver

- tensorflow_serving/util/json_tensor.cc
- tensorflow_serving/util/json_tensor_test.cc
Such numbers are converted to scientific notation (by StrCat()).
The code suffixed such numbers with '.0' yielding invalid numbers.
As an example before this fix, 9000000 would get string converted
(incorrectly) to 9e+06.0 instead of 9e+06 -- the latter is correct.
Similarly .00003 gets converted incorrectly to 3e-5.0 instead of
3e-5
Fixes https://github.com/tensorflow/serving/issues/989
PiperOrigin-RevId: 204536301
(cherry picked from commit 6ff5d9f80ef4ae7b69af2e114fed969c163d6c47)
> Fix erroneous formatting of numbers that are larger than 6 digits.

- tensorflow_serving/g3doc/custom_source.md
The `FileSystemStoragePathSource` now supports configurable `servable version policy` and reports multiple versions rather than the "latest one version" (which could be incorrect even when the ` servable version policy` is  set as `Latest`).
> update guide doc for custom source

- tensorflow_serving/g3doc/docker.md
- tensorflow_serving/model_servers/main.cc
- tensorflow_serving/model_servers/server.cc
- tensorflow_serving/model_servers/server.h
- tensorflow_serving/model_servers/server_core.cc
- tensorflow_serving/model_servers/server_core.h
- exposed `max_num_load_retries ` and `load_retry_interval_micros` as flags of ModelServer
- fixed wrong docker file path at docker readme 
solved https://github.com/tensorflow/serving/issues/1099
> make max_num_load_retries and load_retry_interval_micros configurable for the build-in model_server

- tensorflow_serving/apis/get_model_status.proto
- tensorflow_serving/g3doc/api_rest.md
- tensorflow_serving/model_servers/BUILD
- tensorflow_serving/model_servers/http_rest_api_handler.cc
- tensorflow_serving/model_servers/http_rest_api_handler.h
- tensorflow_serving/model_servers/http_rest_api_handler_test.cc
- tensorflow_serving/model_servers/tensorflow_model_server_test.py
- tensorflow_serving/util/status.proto
This API is not ready for primetime just yet. Instead of making
incompatible API changes in subsequent releases, its prudent to
skip this release and release the first version of this API in
next release.
This reverts commit 00e459f1604c40c073cbb9cb92d72cb6a88be9cd.
> Revert new REST API to get status of models known to the ModelServer

- tensorflow_serving/tools/docker/Dockerfile.devel-gpu
Breaks GPU Docker builds.
This reverts commit 1ac5f399de11f7abc1e0e114c36e5154dbd012e0.
> Revert "Fix missing NCCL header path"

- tensorflow_serving/util/json_tensor.cc
- tensorflow_serving/util/json_tensor_test.cc
Add error messages for specific cases when json for REST requests is not formatted correctly to assist in debugging calls. Previously
error messages return the same error message for
* Both inputs and instances existed
* Value was not an array when array expected
* Empty array
* When examples key was missing for method classify
This is an minor issue I had during debugging and noticed one stackoverflow as well
https://stackoverflow.com/questions/52534843/how-to-use-predict-api-of-tensorflow-serving
https://stackoverflow.com/questions/51776489/correct-payload-for-tensorflow-serving-rest-api
> Add descriptive error messages for invalid json for REST requests

- tensorflow_serving/g3doc/serving_basic.md
As indicated by the warning message in mnist_saved_model.py line 90, the code snippet in the tutorial should be updated to reflect the latest version of mnist_saved_model.py
> Update the code snippet in tutorial to reflect the latest version of mnist_saved_model.py

- tensorflow_serving/g3doc/serving_kubernetes.md
Added space to bash command to allow for copy pasting
> Need space after curl `filename`

- tensorflow_serving/g3doc/serving_basic.md
According to the warning message (line 90) in mnist_saved_model.py, the code snippet in the tutorial should be kept up-to-date. The original line in the tutorial code snippet also creates confusion.
> Update the tutorial code snippet to match the latest mnist_saved_model.py

- tensorflow_serving/model_servers/http_server.cc
Fix to follow [this sentence](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/config/monitoring_config.proto#L12).
> Fix default path of metrics endpoint

- tensorflow_serving/model_servers/main.cc
- tensorflow_serving/model_servers/server.cc
- tensorflow_serving/model_servers/server.h
- tensorflow_serving/model_servers/tensorflow_model_server_test.py
One typical deployment model for Tensorflow Serving is to run it as a sidecar container. With this approach the model is often served over HTTP through a loopback interface. For performance reasons it would make sense to offer a possibility to access Serving over UNIX sockets. This would remove TCP overhead and reduce context switching.
This PR adds a new CLI flag `--grpc_socket_path`. If defined, Serving will listen to a UNIX domain socket at this path. It can be a relative or an absolute path. Note that abstract UNIX sockets are not supported with gRPC. There is an issue about this at https://github.com/grpc/grpc/issues/4677.
> Add support for listening gRPC over UNIX socket

- tensorflow_serving/model_servers/main.cc
- tensorflow_serving/model_servers/server.cc
- tensorflow_serving/model_servers/server.h
- tensorflow_serving/tools/docker/Dockerfile.devel-mkl
- tensorflow_serving/tools/docker/Dockerfile.mkl
Related to #1237 
This PR will add new flags `tensorflow_inter_op_parallelism` and `tensorflow_intra_op_parallelism` to configure values separately. 
To avoid any issues still we support backward compatibility for `tensorflow_session_parallelism`.
Logic goes as below
if either `tensorflow_inter_op_parallelism` OR `tensorflow_intra_op_parallelism` are set, then use those values and ignore `tensorflow_session_parallelism`; if `tensorflow_session_parallelism` is set as well, generate a error message. If neither `tensorflow_inter_op_parallelism` or `tensorflow_intra_op_parallelism` is set, then use `tensorflow_session_parallelism`.
**NOTE:** we'd like the single `tensorflow_session_parallelism` variable to be deprecated in favor of the two `tensorflow_inter_op_parallelism` and …
> [FEATURE]: Split tensorflow_session_parallelism for optimal performance

- tensorflow_serving/model_servers/tensorflow_model_server_test.py
tf.function() is NOT part of TF 1.13 release, causing this test to break on 1.13 branch.
This reverts commit 64f50602342e3a998f87b5340ed40082ab650fcb.
> Revert "Add a tf.saved_model.save / tensorflow_serving integration test"

- README.md
overview.md doesn't exist, pointing to architecture.md
> Updates README with link to architecture overview

- tensorflow_serving/tools/pip_package/setup.py
Use `===` operator for version matching as `=` only supports numbers.
> Fix version matching

- tensorflow_serving/example/resnet_warmup.py
Using the resnet example with a model converted for TensorRT, I was finding
that the first interface request was timing out, while subsequent requests
all worked. I figured a warmup request file would solve this issue, but
I didn't find an end to end example online on how to do this.
I thought it would be beneficial if TensorFlow Serving included
such example. The generated tf_serving_warmup_requests does solve
the issue of the first interface request timing out.
> Example of creating tf_serving_warmup_requests

- tensorflow_serving/g3doc/serving_config.md
Fixes typo in tensorflow serving documentation. Also referenced as part of issue #1413
> fix typo in flag

- tensorflow_serving/model_servers/http_rest_api_handler.cc
- tensorflow_serving/model_servers/http_rest_api_handler_test.cc
- tensorflow_serving/util/json_tensor.cc
- tensorflow_serving/util/json_tensor.h
- tensorflow_serving/util/json_tensor_test.cc
Fixes #1600
PiperOrigin-RevId: 310921928
(cherry picked from commit e1ceccbde64272fbe09915cc34053ad44648447e)
> Return error strings that conform to JSON specs, to prevent malformed JSON responses that fail to parse.

- tensorflow_serving/tools/pip_package/setup.py
The API package itself is a collection of .proto files, and should be
compatible with Python 3.7. Underlying dependencies: protobuf and grpcio
both support Python 3.7, so we can too.
Fixes #1640
PiperOrigin-RevId: 313979135
(cherry picked from commit 3a0bdbe5c216e4eeab8110cad8d959d21a2e376a)
> Add Python 3.7 as supported for tensorflow-serving-api package.

- tensorflow_serving/tools/docker/Dockerfile.gpu
PiperOrigin-RevId: 314861537
(cherry picked from commit 74ea413db4407c1affe2b9fa69dc53ecdba61fa6)
> Install cuda-nvrtc 10.1 into release tf serving gpu docker image.

- tensorflow_serving/batching/README.md
Putting "infinity" in the doc might confuse users that could believe
that "infinity" is a possible value that can be set in the confirguration
files.
See this question on StackOverflow:
https://stackoverflow.com/q/64552963/7370153
And the relevant quote from the question:
> Still, the suggestion in the documentation that some "infinity"
> value exists is giving me restless sleep. How can I indicate
> infinity here?
> changing "infinity" to "really high value"

- tensorflow_serving/tools/pip_package/setup.py
Replace `grpcio>=1.0<2` with `grpcio>=1.0,<2`
This typo makes `conda env export` crash.
> Fix typo in REQUIRED_PACKAGES for grpcio

- tensorflow_serving/util/net_http/server/internal/evhttp_request.cc
The warning is 
```
evhttp_request.cc:260:29: error: null argument where non-null required (argument 2) [-Werror=nonnull]
260 |     if (content_encoding != nullptr) {
|                             ^~~~~~~
```
GetRequestHeader will always return a valid string_view, there is no need to explicitly compare it to nullptr.
> Fix a compile warning thrown by gcc-9

- tensorflow_serving/model_servers/main.cc
- tensorflow_serving/model_servers/server.cc
- tensorflow_serving/model_servers/server.h
Add set max gprc server threads to avoid memory increasing a lot when TF serving start and receive messages.
```
::grpc::ResourceQuota res_quota;
res_quota.SetMaxThreads(server_options.grpc_max_threads);
builder.SetResourceQuota(res_quota);
```
If there is no max threads, then Grpc server will create a lot of threads if first comming messages hang during TF lazy Initialization.
You can check Grpc server source code :
https://github.com/grpc/grpc/blob/659f5e18e4811903a113bc5aa5dd0832523763ba/src/cpp/thread_manager/thread_manager.cc#L149
```
if (!shutdown_ && num_pollers_ < min_pollers_) {
if (grpc_resource_user_allocate_threads(resource_user_, 1)) {
// We can allocate a new poller thread
num_pollers_++;
num_threads_++;
if (num_threads_ > max_active_threads_sofar_) { …
```
> Add grpc_max_threads

- tensorflow_serving/model_servers/main.cc
- tensorflow_serving/model_servers/server.cc
Option to disable TF serving on grpc over http when TF serving starts on unix domain socket. 
Current Problem statement
Describe the problem the feature is intended to solve
There isn't a way to just run TF serving on unix domain socket only, as by default TF serving is started with grpc over http on port 8500.
In multi-user system TF serving running over network have disadvantage. Programs on the same host are able to connect to TF serving. Below are some challenges to secure TF server and clients:
Authorization : To restrict other programs access to TF serving APIs, authorization business logic is required by TF serving.
TLS connection : Since same network namespace is used, client connection to TF serving needs to be encrypted so that other user application can't listen.
An amazing and …
> setting flag --grpc_port=0 disables gRPC over TCP port (Fixes #1764) 

- .bazelrc
This reduces the startup time on GPUs and is in line with TF 2.3 changes
> Specifying compute capabilities in the TF 2.2 .bazelrc file

- .bazelrc
- tensorflow_serving/tools/docker/Dockerfile.devel-mkl
- tensorflow_serving/tools/docker/Dockerfile.mkl
This is really just #1818 for `r2.4` since cherry-pick is not the right way to do it and of course fixes #1797 for the release branch.
Here is how I built it:
```
docker build -f Dockerfile.devel-mkl --build-arg TF_SERVING_BAZEL_OPTIONS='--local_ram_resources=HOST_RAM*0.8 --local_cpu_resources=HOST_CPUS-4' --build-arg TF_SERVING_VERSION_GIT_BRANCH=r2.4 --build-arg TF_SERVING_VERSION_GIT_COMMIT=HEAD --build-arg BAZEL_VERSION=3.0.0 . -t tf-serving-not-based-on-ubuntu:intel-tf-serving-r2.4
```
and here is my output:
```
Step 1/29 : FROM ubuntu:18.04 as base_build
---> c090eaba6b94
Step 2/29 : ARG TF_SERVING_VERSION_GIT_BRANCH=master
---> Using cache
---> 123f3b33ba2a
Step 3/29 : ARG TF_SERVING_VERSION_GIT_COMMIT=HEAD
---> Using cache
---> 67afd58aac1b
Step 4/29 : LABEL maintainer="Abolfazl …
```
> [INTEL MKL] Fix TensorFlow serving build issue for MKL dockerfiles

- tensorflow_serving/model_servers/http_rest_api_handler.cc
This PR just removes an unused variable.
> Remove an unused variable from HttpRestApiHandler::ProcessRequest

- tensorflow_serving/model_servers/http_rest_api_handler.cc
- tensorflow_serving/model_servers/http_rest_api_util.cc
- tensorflow_serving/model_servers/http_rest_api_util.h
- tensorflow_serving/model_servers/http_server.cc
- tensorflow_serving/model_servers/main.cc
- tensorflow_serving/model_servers/server.cc
- tensorflow_serving/model_servers/server.h
- tensorflow_serving/model_servers/server_core.h
- tensorflow_serving/util/net_http/server/internal/evhttp_server.cc
I was making a chatbot webapp, and I found out that I cannot directly call tensorflow serving API because it's missing the CORS headers.
I thought it will be cool if my front-end app can directly call the tensorflow serving API without creating a load balancer.
> add cors headers in http response

- .bazelrc
https://github.com/tensorflow/tensorflow/blob/aa44812e3e40b1c95586466bc177b07525b787ea/.bazelrc#L227
to TF Serving. This causes TF sources to be built with correct
options (bazel options are not picked from relevant dependent
repo (TF in this case), when building code from that repo).
PiperOrigin-RevId: 369022405
(cherry picked from commit 46694d03ef9287d72f856b2a4a159381ff645815)
> Fix broken GPU build by adding TF cuda options

- tensorflow_serving/tools/docker/Dockerfile.devel
- tensorflow_serving/tools/docker/Dockerfile.devel-gpu
pip 21.0 dropped support for Python 2 and 3.5 (https://pip.pypa.io/en/stable/news/#v21-0).
Use Please use https://bootstrap.pypa.io/pip/2.7/get-pip.py instead.
> Update pip source for python 2.7 #1

- tensorflow_serving/g3doc/docker.md
Fix nvidia-docker link at "Serving Docker using your GPU"
> Fix nvidia-docker link at Serving Docker using your GPU

- tensorflow_serving/util/net_http/client/test_client/internal/BUILD
- tensorflow_serving/util/net_http/client/test_client/internal/README.md
- tensorflow_serving/util/net_http/client/test_client/internal/evhttp_connection.cc
- tensorflow_serving/util/net_http/client/test_client/internal/evhttp_connection.h
- tensorflow_serving/util/net_http/client/test_client/public/BUILD
- tensorflow_serving/util/net_http/client/test_client/public/README.md
- tensorflow_serving/util/net_http/client/test_client/public/httpclient.h
- tensorflow_serving/util/net_http/client/test_client/public/httpclient_interface.h
- tensorflow_serving/util/net_http/client/test_client/testing/BUILD
- tensorflow_serving/util/net_http/client/test_client/testing/evhttp_echo_client.cc
- tensorflow_serving/util/net_http/server/internal/BUILD
- tensorflow_serving/util/net_http/server/internal/evhttp_request_test.cc
- tensorflow_serving/util/net_http/server/internal/evhttp_server_test.cc
Copied the old client to the new “test_client” package and updated all the unit tests that use this client. Also added 'Test' Prefix to all classes and structs. All this is done to clear space for the development of a new public http client API. @wenbozhu will help upgrade all existing google-internal call sites of the old client. After that, I will delete everything directly under net_http/client.
> Copy old client to new package and updated unit tests

- tensorflow_serving/tools/docker/Dockerfile
- tensorflow_serving/tools/docker/Dockerfile.devel
- tensorflow_serving/tools/docker/Dockerfile.devel-gpu
- tensorflow_serving/tools/docker/Dockerfile.devel-mkl
- tensorflow_serving/tools/docker/Dockerfile.gpu
- tensorflow_serving/tools/docker/Dockerfile.mkl
PiperOrigin-RevId: 488422181
(cherry picked from commit d8555724ed54f3102952f9eca5a7d2b695899e20)
> Upgrade to ubuntu20.04 for docker images, which defaults to gcc-9.

- .github/workflows/stale.yaml
In this PR:
Increased the no. of operations per run from 30 to 1000 to pick more issues and PRs.
Add Override stale .
Prevent to remove stale label when issues/PRs update.
> Increase rate limit, override stale and remove stale to false for stale Github action. 

- third_party/tensorflow/tensorflow.patch
Original change does not resolve breakage.
This reverts commit 984448fc724adf326af538182dcfbc177d6b15fd.
> Revert "Fix for gcc10 breakage."
