tensorflow_serving/batching/streaming_batch_scheduler.h, tensorflow_serving/core/dynamic_manager.h, tensorflow_serving/core/servable_handle.h, tensorflow_serving/example/mnist_inference_2.cc, tensorflow_serving/util/any_ptr.h, tensorflow_serving/util/fast_read_dynamic_ptr.h, tensorflow_serving/util/optional.h
None of these spelling changes seem important but I came across them while understanding how the project works and thought I'd send a pull request.
=> Minor spelling changes in misc comments.

tensorflow_serving/example/mnist_inference.proto
Noticed these errors while reviewing the example code.
=> Boring old comment fix

tensorflow_serving/example/inception_export.py
ouput predicted index must be subtracted by 1
=> Fix a bug that returns class string incorrectly

tensorflow_serving/example/inception_client.py, tensorflow_serving/example/inception_export.py
=> Removed unused imports from inception python examples

tensorflow_serving/model_servers/BUILD, tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc, tensorflow_serving/sources/storage_path/file_system_storage_path_source.h, tensorflow_serving/sources/storage_path/file_system_storage_path_source.proto, tensorflow_serving/sources/storage_path/file_system_storage_path_source_test.cc
Upstream changes from internal
=> Branch 130454325

WORKSPACE, tensorflow_serving/workspace.bzl
This is not a complete change since it requires to update
the dependency to tensorflow itself.
=> Make tensorflow new cuda auto-configuration works

tensorflow_serving/example/inception_client.py, tensorflow_serving/example/inception_export.py, tensorflow_serving/example/mnist_client.py, tensorflow_serving/example/mnist_export.py, tensorflow_serving/example/mnist_input_data.py
- Ran 2to3 converter to add parentheses for print statement 
- xrange replaced for range
=> Fix inception and mnist examples for Python 3

tensorflow_serving/batching/batching_session.cc, tensorflow_serving/core/aspired_versions_manager.cc, tensorflow_serving/core/basic_manager.cc, tensorflow_serving/core/basic_manager_test.cc, tensorflow_serving/core/dynamic_source_router_test.cc, tensorflow_serving/core/static_manager.h, tensorflow_serving/core/test_util/BUILD, tensorflow_serving/example/BUILD, tensorflow_serving/g3doc/serving_basic.md, tensorflow_serving/g3doc/setup.md, tensorflow_serving/g3doc/signature_defs.md, tensorflow_serving/model_servers/BUILD, tensorflow_serving/model_servers/main.cc, tensorflow_serving/model_servers/server_core_test.cc, tensorflow_serving/model_servers/tensorflow_model_server_test.py, tensorflow_serving/model_servers/test_util/server_core_test_util.cc, tensorflow_serving/model_servers/test_util/server_core_test_util.h, tensorflow_serving/servables/hashmap/hashmap_source_adapter_test.cc, tensorflow_serving/servables/tensorflow/classifier_test.cc, tensorflow_serving/servables/tensorflow/regressor_test.cc, tensorflow_serving/servables/tensorflow/testdata/BUILD, tensorflow_serving/servables/tensorflow/testdata/batching_config.txt, tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc, tensorflow_serving/workspace.bzl
Upstream changes from internal
=> Branch 149617468

tensorflow_serving/g3doc/serving_inception.md
Based on documentation at: https://cloud.google.com/container-registry/docs/pushing
=> Fix gcloud docker image push command

tensorflow_serving/g3doc/serving_inception.md
based on documentation at: https://kubernetes.io/docs/user-guide/deployments/#creating-a-deployment
=> Fix for command to get deployments

tensorflow_serving/example/inception_k8s.yaml
Fix the Selector  section of Service to the Deployment
=> FIx service selector

tensorflow_serving/tools/docker/Dockerfile.devel
Dockerfile:
* updated ubuntu to 16.04
* removed unnecessary ppa of JDK8
* updated bazel to 0.5.1
* removed unnecessary hacks for bazel
* updated python modules
=> Updated Dockerfile, some cleanup, remove redundant stuff

tensorflow_serving/g3doc/leftnav_files
Add metadata that gives ordering to left navigation.
=> Leftnav update

tensorflow_serving/g3doc/leftnav_files
Include missing page to appear on main site.
=> Add index to leftnav

tensorflow_serving/g3doc/index.md
To exist on main site, a title is required.
=> Add title to pick up TOC

tensorflow_serving/core/servable_handle.h
https://github.com/tensorflow/serving/issues/561
=> Remove unnecessary dependency servable_handle.h

tensorflow_serving/util/class_registration.h
Fixes issue https://github.com/tensorflow/serving/issues/613
=> check for UnpackTo return value when parsing platform_config file

tensorflow_serving/g3doc/architecture_overview.md
Unsure if I've changed the meaning. If I did, that was accidental. I found this section difficult to read and hope this is clearer.
=> Rewrote (simplified) "sources" presentation.

tensorflow_serving/g3doc/setup.md
Related Issue: https://github.com/tensorflow/tensorflow/issues/13805
=> Add note about the TensorFlow Serving Python API for Python 3.5.

tensorflow_serving/apis/BUILD, tensorflow_serving/apis/model_management.proto, tensorflow_serving/apis/model_service.proto, tensorflow_serving/model_servers/model_service_impl.cc, tensorflow_serving/model_servers/model_service_impl.h
Added gRPC API for model config reload.
=> Runtime model config reload gRPC API

tensorflow_serving/util/class_registration.h
This issue was discussed in #868 .
=> change config pointer address compare to full_name compare

tensorflow_serving/tools/docker/Dockerfile.devel, tensorflow_serving/tools/docker/Dockerfile.devel-gpu, tools/bazel.rc
Similar to https://github.com/tensorflow/serving/pull/980 (that went into r1.9 branch)
=> Dockerfile fixes from master

tensorflow_serving/g3doc/docker.md
The original doc has an unexpected newline at the `*` character.
=> minor doc fix

tensorflow_serving/g3doc/docker.md, tensorflow_serving/tools/docker/Dockerfile, tensorflow_serving/tools/docker/Dockerfile.devel, tensorflow_serving/tools/docker/Dockerfile.devel-gpu, tensorflow_serving/tools/docker/Dockerfile.gpu, tensorflow_serving/tools/docker/README.md, tensorflow_serving/tools/pip_package/BUILD, tensorflow_serving/tools/pip_package/build_pip_package.sh, tensorflow_serving/tools/pip_package/setup.py, tools/bazel_in_docker.sh
Cherry pick docker and pip changes from master. Notable changes:
- Fix broken PIP packages (#999)
- Updated Docker GPU configs (#1005)
- New GPU runtime docker image
=> Docker and PIP packaging fixes from master

tensorflow_serving/tools/docker/Dockerfile.devel, tensorflow_serving/tools/docker/Dockerfile.devel-gpu, tools/bazel_in_docker.sh
PiperOrigin-RevId: 208535314
(cherry picked from commit b2d2b87d67ec065ae1e4df4ca5b36c151d6457f6)
=> Update docker builds

tensorflow_serving/tools/pip_package/build_pip_package.sh, tensorflow_serving/tools/pip_package/setup.py
PiperOrigin-RevId: 208718607
(cherry picked from commit fc8c5301125903a3e2ddc8b743f78f0d539bf61b)
=> Keep pypi package from overwriting TF package

tensorflow_serving/tools/docker/Dockerfile.devel, tensorflow_serving/tools/docker/Dockerfile.devel-gpu
PiperOrigin-RevId: 208891157
(cherry picked from commit aed1ae7e406d511e648709239411fcd0681b5ac0)
=> Update docker images

tensorflow_serving/tools/pip_package/BUILD, tensorflow_serving/tools/pip_package/build_pip_package.sh
=> Add missing dependency to tensorflow-serving-api build_pip_package

WORKSPACE, tensorflow_serving/model_servers/BUILD, tensorflow_serving/tools/pip_package/setup.py
Reverts tensorflow/serving#1087
=> Revert "Update version for 1.11.0-rc0 release."

tensorflow_serving/util/BUILD, tensorflow_serving/util/prometheus_exporter_test.cc
PiperOrigin-RevId: 212981021
(cherry picked from commit fdf23de9993c0fef83ce5a4029cd2ed8582039a8)
=> Add missing include.

tensorflow_serving/repo.bzl
- Corrected http_archive spelling in comments.
=> Update: Corrected http_archive spelling

tensorflow_serving/g3doc/setup.md
Hi,
This PR fixes a couple of minor issues with the setup documentation. It:
1. Removes the term `shell` appearing in the rendered text.
2. Adds the `update` command before the `install` command.
Hope this helps.
Thanks!
=> Minor update in setup documentation

tools/bazel_in_docker.sh
=> Add `-N` to useradd.

WORKSPACE, tensorflow_serving/model_servers/BUILD, tensorflow_serving/model_servers/version.h, tensorflow_serving/tools/pip_package/setup.py
=> Update version for 1.12.0-rc0 release.

tensorflow_serving/tools/docker/Dockerfile.mkl
Update comments as new envs TF_NUM_INTEROP_THREADS and TF_NUM_INTRAOP_THREADS are added in tensorflow.
=> Update comments in MKL dockerfile

tensorflow_serving/util/net_http/server/internal/evhttp_server.cc
=> ignore SIGPIPE, fix issue #1257

tensorflow_serving/g3doc/serving_config.md
Modify docs for monitoring config.
From https://github.com/tensorflow/serving/issues/462#issuecomment-487604886
=> Add monitoring config

tensorflow_serving/tools/pip_package/setup.py
PiperOrigin-RevId: 250520004
(cherry picked from commit 4aa0cfc24098000163fdfe270c4eb205e98790b1)
=> Remove hyphen from version numbers to conform with PIP.

tensorflow_serving/tools/docker/Dockerfile.devel, tensorflow_serving/tools/docker/Dockerfile.devel-gpu, tensorflow_serving/tools/docker/Dockerfile.devel-mkl, tensorflow_serving/tools/pip_package/setup.py
While building `mkl` development container from tip of the `master` I noticed we are getting this error:
https://github.com/tensorflow/serving/pull/1367#discussion_r289581902
This PR is an attempt to fix that issue.
=> Fix ImportError: No module named builtins

tensorflow_serving/util/json_tensor.cc, tensorflow_serving/util/json_tensor_test.cc
Fixes https://github.com/tensorflow/serving/issues/1610
=> Allow batch size of zero in row format JSON

tensorflow_serving/util/json_tensor.cc, tensorflow_serving/util/json_tensor_test.cc
Fixes #1615 
PiperOrigin-RevId: 312314660
(cherry picked from commit fb167400cab14600c86765b6415da164c4a3e0aa)
=> Allow batch size of zero in row format JSON #1615

tensorflow_serving/model_servers/prediction_service_impl.cc, tensorflow_serving/model_servers/prediction_service_impl.h, tensorflow_serving/model_servers/tensorflow_model_server_test.py
Fixes #1612
PiperOrigin-RevId: 312723939
(cherry picked from commit c1ce0752f1076bd6f92e1af5f73e3a3c552f4691)
=> Fix broken GetModelMetadata request processing.

tensorflow_serving/g3doc/serving_basic.md
This fixes https://github.com/tensorflow/tensorflow/issues/38523
=> fix broken web link

tensorflow_serving/workspace.bzl, third_party/icu/BUILD, third_party/icu/README, third_party/icu/data.patch
Cherry-pick of master commit. https://github.com/tensorflow/serving/commit/c32ebd5e9f09828c80413ca989b99e8544502c1a
PiperOrigin-RevId: 313662726
=> Update ICU library to include knowledge of built-in data files.

tensorflow_serving/workspace.bzl, third_party/tf_text/tftext.patch
Cherry-pick of master commit https://github.com/tensorflow/serving/commit/f8ea95d906421ff9517b0027662546741c486edf#diff-621bd2ac68386e4fe31937ab32647fcb
PiperOrigin-RevId: 311360445
=> Fix tftext version f8ea95d

.bazelrc
PiperOrigin-RevId: 325552145
(cherry picked from commit 9186b1a465211fc7f334025a922914949c5e2471)
=> Set cuda compute capabilities for `cuda` build config.

tensorflow_serving/tools/pip_package/build_pip_package.sh
=> Fix release script

tensorflow_serving/example/resnet_k8s.yaml
The Kubernetes deployment file is outdated.  kubectl will reject the deployment. 
Update the resnet_k8s.yaml file
=> update resnet_k8s.yaml file

tools/run_in_docker.sh
Signed-off-by: Hao Ziyu <haoziyu001@gmail.com>
=> Update the comments

WORKSPACE, tensorflow_serving/model_servers/BUILD, tensorflow_serving/tools/pip_package/setup.py
Update version for 2.4.0 Final Release.
=> Update version for 2.4.0 release.

tensorflow_serving/tools/docker/tests/docker_test_lib.sh
PiperOrigin-RevId: 355546760
(cherry picked from commit f92ac94bf5d597582065198e9ff50e6eeb50c078)
=> Cherry pick the potential test fix to 2.4

tensorflow_serving/tools/docker/Dockerfile.devel
TF 2.1.4 supports Python 3.6 and Python 3.7 (https://pypi.org/project/tensorflow/2.1.4/#files)
=> Update docker file to use python3.6

tensorflow_serving/workspace.bzl, third_party/tf_text/tftext.patch
Update TF Text to v2.4.3. Picking up changes from https://github.com/tensorflow/serving/commit/ccfb606b2c86f4ffb57ecd8454c8809ab8c13090#diff-bd436285f77efec760a31396a2280da70086b990f946fc7759ca58b137c2069f
=> Update TF Text to v2.4.3.

tensorflow_serving/tools/docker/Dockerfile.devel, tensorflow_serving/tools/docker/Dockerfile.devel-mkl
PiperOrigin-RevId: 425544723
(cherry picked from commit 140bbe7d4f6440449b61b360f227da6851b6332b)
=> Fix the bug running get-pip.py on python3.6.

.github/workflows/stale.yaml
In this PR:
- Changed issue stale days to 7 from 14.
- Changed issue close days after stale to 7 form 14.
=> Update file stale.yaml. 

tensorflow_serving/tools/docker/Dockerfile.devel, tensorflow_serving/tools/docker/Dockerfile.devel-gpu, tensorflow_serving/tools/pip_package/setup.py
PiperOrigin-RevId: 519799120
(cherry picked from commit 68d92ff3fdca0641f465cc3ba3858a619c8b82a6)
=> Update Dockerfile.devel* with py3.8 installed.

tensorflow_serving/g3doc/api_rest.md
Fixed the broken link for setup instructions in line 430
=> Fixed the broken link in api_rest.md

tensorflow_serving/tools/docker/Dockerfile.devel, tensorflow_serving/tools/docker/Dockerfile.devel-gpu, tensorflow_serving/tools/pip_package/setup.py
PiperOrigin-RevId: 559891667
(cherry picked from commit 07f9ba50ebf75991ef27541c8a318de76886c5f6)
=> Update Dockerfile.devel* with py3.9 installed.

tensorflow_serving/tools/docker/Dockerfile.devel-gpu
=> Pin libnvinfer headers versions.

.bazelrc, WORKSPACE, third_party/tensorflow/tensorflow.patch
Adding patch files of commits 
https://github.com/tensorflow/tensorflow/commit/130d583ff62c506156faf4077fd7c23798378d2f 
https://github.com/tensorflow/tensorflow/commit/a2bda8862811c8f15c09b43bffb67fa2dc460f71
and manually added 
https://github.com/tensorflow/serving/commit/19f9ccf9a3ddedc93812da7eac28554ebbc1f8dc.
=> Include patch files necessary for building at TF 2.17

tensorflow_serving/tools/pip_package/setup.py
=> Mark Tensorflow compatible with Protobuf v26+.

third_party/tensorflow/tensorflow.patch
=> Added github.com/openxla/xla/pull/22572 into tensorflow.patch to resolve breakage.

tensorflow_serving/tools/pip_package/setup.py
=> Mark Tensorflow compatible with Protobuf v30+.
